apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:fcfXXpr/D6XmFlO+2lmZz5gvwRopTIddmCf4W5F2dAnXgAOlX/gDwj4x3OlmuEcwq+qxd3cPbLmI7sf1kTKWKbOgxBS9NGET,iv:xRkCTjkKS+65qOFDIGva5VlAKsK7XT/E5hjfxCGeFAM=,tag:cbsUe+Zaoi9zWYp5Tr8MmA==,type:str]
sops:
    lastmodified: "2026-04-01T07:06:40Z"
    mac: ENC[AES256_GCM,data:4KxipZKW2eReezwfDqW5M22Z2MJhAz8nHMJ1UsfU3lDocD0e1XFZK6GidXFsRwSiGvwhp6YTkxeW3ls7nnJmsXgSHihGpQAOg6AGr7vxKhhAvKua/5F0QGf9yJYhdLIu4FzmrJQD+Z7gJToVKZnV2ThC6yQaHmYLWGa/8EAqSIE=,iv:pvknItST3QFrX9cXWyENm6YMlLHtvovyaX2WbLJNVmU=,tag:saynjNEAXnnJaMHGWdtA7A==,type:str]
    pgp:
        - created_at: "2026-04-01T07:06:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DcDhmFWror8ASAQdArwZYIcD6suYH2t1OywSqByv4msy1EvCrLQVHLEym9kkw
            orUnO6FikZLBuDUhYoeKwWApRr4OzBWeiU6IvZ6Atgks18YDFeqH9XI+f+lFdHKz
            1GgBCQIQg7g5nes/NBLqi5SWUnsAU5k81YeY+5szQr9DhOrXupMu0Omvw8vo6vEJ
            ZTga0S/fDRAcJlsY0KoNUp24V7/8csOEGSa+eIp/5AuTRcSbc/yn5p0r6+SWjzZl
            ysiFqTkp/CHp3g==
            =ePxP
            -----END PGP MESSAGE-----
          fp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B
    encrypted_regex: ^(ca|crt|id|secret|secretboxEncryptionSecret|secretboxencryptionsecret|token|bootstraptoken|key|environment|TS_AUTHKEY)$
    version: 3.10.2
