apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:0oJ1TooZ8zMxy11D+McF5otlGEuTAaS8/ki/zJzc0IZzTTQiYFHXzL/wk8phUElMn8f3A1oDTlcTQVUY9+AWA/B5Ex8CmpmI,iv:RVVn+4mfrgKZJHVeSBhxkDEGeOawFpac6Evkuk9slKQ=,tag:OJ1OXzuTd0wqOa969TQkNA==,type:str]
    - ENC[AES256_GCM,data:OYNQN6eV677o3lBZGizphGHxLiMJMpNRH+kq4K9edQ==,iv:5B4Tyfj3CBFXiJq25/eYGYgpSilutnvsB03ayXKB9To=,tag:keQj6n0G8d7fKdq/H56jyw==,type:str]
sops:
    lastmodified: "2026-04-28T15:09:58Z"
    mac: ENC[AES256_GCM,data:CTHkSskZLjeotFI7AaHgZBO/GBWmlwmw8P55JxwFB9bndKxXqBXjM+1ov6kBo69+FkwwW0y4VVeXGEJCKJiLIFLxW4zn5za8BD5/XUFLFXq2wueFp9KHbNStLYhQPnPWuH0VY4A1g7kfQoZHb7xoD/D7Hq179UtUIhvJ9RyU3Qc=,iv:QaruhGfSgGEJvWtnxSCwO7QulWidwsn9BVCz0eRCBrw=,tag:vy5BQHnoqkZwsPhy8aiC2w==,type:str]
    pgp:
        - created_at: "2026-04-28T15:09:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DcDhmFWror8ASAQdA6LX9k043fgf8nI5yR86HwkB/1n+aNkeblrrymhdF4Ssw
            061icagUwdjrVQONEaSHazT/GgIM1snEho2RuLvmzK6MglUTMCvUFmOfpJSE6z7o
            1GgBCQIQ8BKxYzP3yh71TzMhlFwYxJM4H0lEE5qZ6wt+cgdV0w2ORTotjbBgWoJz
            0UQwiHgqRQpRGZ6kv5PqReOzjqNjNarm35P2vTx7yxZ2gEY5T/0F03g6R5LfX6Of
            pP9RybcVTCqVaA==
            =hfqj
            -----END PGP MESSAGE-----
          fp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B
    encrypted_regex: ^(ca|crt|id|secret|secretboxEncryptionSecret|secretboxencryptionsecret|token|bootstraptoken|key|environment|TS_AUTHKEY)$
    version: 3.10.2
