apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:6/zGSobXfEQFhDEH6iqyJtLJBlGzINQoz92K9L3lY0CjWa+5I8YUTkNdKOvyB29Vs6+bO5/rl6ckjwl/1J7IeCKdxGYagt3M,iv:E1WMOak5rHjLuxkJ6YWScu9M2zYS1ZEZ1b4v+bCTicg=,tag:vP9fpCKAHNaFfY0R7NVMyw==,type:str]
    - ENC[AES256_GCM,data:OYNQN6eV677o3lBZGizphGHxLiMJMpNRH+kq4K9edQ==,iv:5B4Tyfj3CBFXiJq25/eYGYgpSilutnvsB03ayXKB9To=,tag:keQj6n0G8d7fKdq/H56jyw==,type:str]
sops:
    lastmodified: "2026-05-04T03:06:06Z"
    mac: ENC[AES256_GCM,data:CuTXSSydyZlRGmGUjxs5ZQOKFnmsA9vScwz8t4fFn/cDZQH+6ScPxmrDGEpr8vigdZZUUFp6wtWY6bMvlLtoWtdvk9hg/kuoCA5XgoBnPuRJUl67+l4iT1mx0UGKed8PMbHdOAxM1sxH+SBS6xdxn8Iy36XtJRLB8BC+RsWOPBs=,iv:krl7WWdRzUlMCqX/kT8RlVD5JkgQs/LHQ75aZUxP9p8=,tag:Jqx7/M4R2bc0UpeSmALEMg==,type:str]
    pgp:
        - created_at: "2026-04-28T15:09:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DcDhmFWror8ASAQdA6LX9k043fgf8nI5yR86HwkB/1n+aNkeblrrymhdF4Ssw
            061icagUwdjrVQONEaSHazT/GgIM1snEho2RuLvmzK6MglUTMCvUFmOfpJSE6z7o
            1GgBCQIQ8BKxYzP3yh71TzMhlFwYxJM4H0lEE5qZ6wt+cgdV0w2ORTotjbBgWoJz
            0UQwiHgqRQpRGZ6kv5PqReOzjqNjNarm35P2vTx7yxZ2gEY5T/0F03g6R5LfX6Of
            pP9RybcVTCqVaA==
            =hfqj
            -----END PGP MESSAGE-----
          fp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B
    encrypted_regex: ^(ca|crt|id|secret|secretboxEncryptionSecret|secretboxencryptionsecret|token|bootstraptoken|key|environment|TS_AUTHKEY)$
    version: 3.10.2
