creation_rules:
  # Talos secrets.yaml files
  - path_regex: secrets\.yaml$
    encrypted_regex: "^(id|secret|bootstraptoken|secretboxencryptionsecret|token|crt|key)$"
    pgp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B

  # Talos machine/cluster config YAML files
  - path_regex: .*\.yaml$
    encrypted_regex: "^(token|secret|endpoint|crt|key|certSANs)$"
    pgp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B

  # Fallback for any other files
  - pgp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B
