apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:WlkNCE8hgcnD84xpb5QhRwYaZgzGBCq9IK8b6ixDTYUT9WpQ7cE+qHtqokTlW8aSVzVgIWw7sUbOZXHdlWnJImzdTfYWTsFuGQ==,iv:kpcQscOgqmBoRYpRi94eJSX2QsuBXmhjOHYIxiuQ4x4=,tag:YuzEMO2up1T8fv6zcrAlmw==,type:str]
sops:
    lastmodified: "2026-04-01T04:06:50Z"
    mac: ENC[AES256_GCM,data:CPwpOx+2509F49gICEdz6/PPrCBW5zxW5KO/xD/MkSSxBkIzl2tz6KbPgyMvcWGek0DnAWqes6z9d9wou/TKapr4kjyyXNx1sw3g7F2wT8RHyYEz4SVnJwtbXyp4vn+6AO5c4qVGc5eJSybHyt1gZ07r4fXe+5BYvQH49S5y668=,iv:s/aMUtbbUV/nAsLv6xUlGYiZf8vsxUDfsGn+ZVfjE1I=,tag:KfGoIxITpPFtOsK/7bBfTw==,type:str]
    pgp:
        - created_at: "2026-04-01T04:06:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DcDhmFWror8ASAQdAUSy35g4szmOHgwpwYDSxhviMrpmhmHMuvZj56vWc9GMw
            W89sZyuPN0cpRrAUCReK3HVhEwAAy8Xo+M1c2L9nDt6K1l9hXOouGGP/d0sdYWYR
            1GgBCQIQmZtqCuv6NdxScYUogJOzeBgY+j49Azq3JSPE03nuT7/p4te6fICCuoze
            61c8zZWCY6cuEHxogXhKFVf5NAeJzL0Zm0JrE0bnEuRMpeyH/DzYOewmCHIv5mv4
            73sGEiNXlqk9DQ==
            =UBpH
            -----END PGP MESSAGE-----
          fp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B
    encrypted_regex: ^(ca|crt|id|secret|secretboxencryptionsecret|token|bootstraptoken|key|environment|TS_AUTHKEY)$
    version: 3.10.2
