apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:frj6YgUpL1xFC0WARuWDz3Fp8C6RXM0Ie/BtHIGsKx4MlC1tAfmNRmx5igPuMSjCiUWNb3Kz2yj+VV77+VaCJcP4KXdkdWKIbA==,iv:uMRP+6/YzuTn8FwQWEWM32qNC0/WHgMhU0CwzYnG6BA=,tag:25HdSeLAYE7+gUD0Rz0i6Q==,type:str]
    - ENC[AES256_GCM,data:FP9Zhp3IcIOVZQ/J68kSKjtyHLbLyzDIoUQRVWFj1A==,iv:1iKkfHJ1da6aAygyD7Iu3m0qYXaGc9Zi/C9Pe2aKcXk=,tag:gYCNn8jL7cbT2EM2Ocq5CA==,type:str]
sops:
    lastmodified: "2026-05-21T14:42:20Z"
    mac: ENC[AES256_GCM,data:kJRzjE/FTTeAO3UXspHAo5RyDkYYzCop7ujzxSutFStpSGnZN2ZWZPXoxBFf174h5eCYDWkBot2405z0CLwQyhRMriZvcfM08BzV/90J5rdR/Hz/2Fdqjp2OrzpPf9z5H/Wtm1kJDdfl+1H7qCXigyfuAdzDhzlV5nvaVA5r1xQ=,iv:uz19U4BDfZnTxrtaI7hlCvDWBPb9R61/Xa6pBXQIQdw=,tag:XopAJjRGeFRDrXZj+QImAw==,type:str]
    pgp:
        - created_at: "2026-05-21T14:42:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DcDhmFWror8ASAQdAmP2rT+mU6oPXRiTBod4wxQRJbt3d6oZNbXSYeMjYfQUw
            EEp0k61FUB07SrqUaG/2WrrvOqu3OaSNqbtI7I8yZLRBZFsKqrHK3Fn2YgTTGgMq
            1GYBCQIQ2dF6sjtJ7bNxUlB3JAbnq2o7nE2Ek567axramyaFZlFRXVlG+4QVkaOo
            DykJIug9ugJlf+BpSmPOX5ldGRITa68HoXihOxmKXBHy4tTAys/r1ARRCXLSLGO6
            dO7l1fd50sY=
            =KXdu
            -----END PGP MESSAGE-----
          fp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B
    encrypted_regex: ^(ca|crt|id|secret|secretboxEncryptionSecret|secretboxencryptionsecret|token|bootstraptoken|key|environment|TS_AUTHKEY)$
    version: 3.10.2
