apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:hR6sYF0odVuwNYlAkxa+QpIuUQewvCBvB/LIeAONBMNfj9fD3xWfEMacHrRHhb7FgMtWWkvf4KDis4GCp3Dv5gw4oClRgeXMcg==,iv:9euZ5OvB4pyTNObJLRCZsZd8nwP5FkcVPJUUw2J5fIg=,tag:uJXSmtr6LnPlSRfuVnw4fA==,type:str]
    - ENC[AES256_GCM,data:HAQAlnKSYiKRHXHI8yjUNREVe6r1HqWTA5jNTEPs8Q==,iv:A81zYByeicZLewTvUYG6ZRwYRelEjMshCf1Ul5gkNbY=,tag:w/2JhyE9U0pwb/EaV5U8fQ==,type:str]
sops:
    lastmodified: "2026-07-23T19:36:05Z"
    mac: ENC[AES256_GCM,data:3fB1RdU9X3++mTtm5QOxcSB/McsgC1eFInqWNrSV+HfIELUyc7OC3MOG5NekBhvX1Zn8k0Nr1rmVKuyjBsvrMu+TJR+9lw8VMWaYAsrdEqpQGbuTHLQ1gP8nfZzURkOr8L1x696spYkS3YPSIZS8sT9UH/uynB4DlnnWeHxYd3k=,iv:cqY1Se2+V/JeNxqcTbDCX7LUQeuijx1UgdLp169AifA=,tag:StcfZoT5lupr05QeFdYZ5w==,type:str]
    pgp:
        - created_at: "2026-07-23T19:36:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DcDhmFWror8ASAQdAVfhKT6LBNM5bmQJ/z/kEUfoTtOtQIq7Gt/Y0+J/bOB0w
            iUm3nI4L17VdRGchEG5GsM4FHduj+K/lhtsVaAUr6uicPCx+gq/n0j5WnfpQVzq0
            1GgBCQIQ6P1Ydf+zZZwbxaDjUelnaGNNOszL4TfbllfRmkoima5oejdK1VW1xTHB
            uarARnH4FdRfqKdceMB+ix1fGkXDtnOHehSWQ8c8qKa1ZD7Qu10uA4iNOZY6pC0N
            7ISdGirijK9Bxw==
            =3AGs
            -----END PGP MESSAGE-----
          fp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B
    encrypted_regex: ^(ca|crt|id|secret|secretboxEncryptionSecret|secretboxencryptionsecret|token|bootstraptoken|key|environment|TS_AUTHKEY)$
    version: 3.10.2
