apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:dw5mxhvL84EyzKWo6QeUHhIbyOz2ikhs6p2Vdp33RSoOozKfZfeLWOyqIGGip/72daISuc9EKpWfL9NMQietLEMfkOYSL/aBJg==,iv:fmQX9f9GxD52cLM7vrlcHMOjyn+5wxdAOVS2v+whQz0=,tag:d/Tn3VSuFOXo9D54+YUCTA==,type:str]
    - ENC[AES256_GCM,data:MkHSSZ/SRuSmko9+XU+3GG7CMXAs3wJmP720tE52/Q==,iv:tBIJUluCVLF1A4I0EtTq9ZKAdpcRoAKUTiENV4WnE5Q=,tag:fB0uOH0MEOLu/GZ3ukY4LQ==,type:str]
sops:
    lastmodified: "2026-05-20T14:47:33Z"
    mac: ENC[AES256_GCM,data:ifcn81pHx6dQkKUbMNB2D0aD0wQ+HXa3rjdLEab8eq3ZSdIloUxlPzgKv54MApLsfuQADvjeiQf3B1LRdnfvTONqZhO1ocWgIDIJ/rYl4Fc2XpM/WrkEsGRgr2p+pUX/s3Yk0ctkBpNgh6oQIPDpA3Os0hRGZYMCSSWM+QzwDnY=,iv:uB8j7H7UckMmQMS83Q6X2IABQ5gSXvoapE2IyXzSPu0=,tag:uH94OhdYJpNyk9zai2/INQ==,type:str]
    pgp:
        - created_at: "2026-04-12T02:10:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DcDhmFWror8ASAQdAtk5V+S5W1JdQg4p3WdUTw+/3C3ywwUoSR1xMZD/oQh0w
            IwXjcOORtga+nOhIjlL0Day9OoqHNb6kkGg79BcMqdA3FZZBtcPWAXJKZUJj+iWf
            1GYBCQIQ9bgtR9aTKW/OVdQdrYa7+/ijZghljccoBuyXwCXYpnmL85vM9bfG555O
            94n9nWLgZRfsYuIRR74EiyKCXrk9dVf7JlEoUsExnya+QKS7Qf5sjUUCgmp1tkzB
            gAB0k0H8/SY=
            =dvNE
            -----END PGP MESSAGE-----
          fp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B
    encrypted_regex: ^(ca|crt|id|secret|secretboxEncryptionSecret|secretboxencryptionsecret|token|bootstraptoken|key|environment|TS_AUTHKEY)$
    version: 3.10.2
