apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:oa8kY/FIMnxKuC1YFbD4aaY4+q03oWuGNvEZg5+1u3/PlSuIv8eZCSpqPcMrL5k/mENkLb3jeR22Y8rJ1/i830lT8xQ7ZedY+A==,iv:4VrKMDalcK7+4zyCkgwKZ/Fmbu3Pd7uXAlaWjUJN4FE=,tag:F2Iy6E22K+edYc7nzcLJvA==,type:str]
    - ENC[AES256_GCM,data:MWwWWJQyI1uAtXz4wDI/BkyGWdpBSUJ+BReO1KSpAA==,iv:Gu0NXHxZMIgV3PhtP/Wr2YMRzeMPvSQ8WI0BtzwWfGs=,tag:fp5EdRfz2eaQO7hUXcwHEQ==,type:str]
sops:
    lastmodified: "2026-05-20T15:29:35Z"
    mac: ENC[AES256_GCM,data:GU7SEG7tyNO0fTppHA+xCseEQ8RLoBROT26HQRsRstbb3VPHPnDs6I6ETN/YYJMZlpzXw5GNXgPcCWcPAgIPcjO1M/4r4r1+3nz53/49Vr8qJvPO6YfXlB42I7W2MuH+XNZXOet4yqx+j8kOfAJ4tsPek5Jd/xkLj0vIEuPqB2Q=,iv:Y7mzSkpLuIURCWQBAy5qFyKCDddaA0tDTC2ERb1sVsg=,tag:Y0Ygkd1GAeUye+az0Q5qvQ==,type:str]
    pgp:
        - created_at: "2026-05-20T15:29:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DcDhmFWror8ASAQdAckdVOINlCv+9sxQe5oN8cY8mczXg4pdP34h6QM3etiow
            Fn9NJuBskuKEYxCCrokm+ZmIKBo0UG/QaB12lc0uB2c6ov2uhavzIIGS0pLvBQQ9
            1GgBCQIQ222jHfyDjorbjb9kN5delk1olx+BjRZYVvQ/i35BHlHGSZrou9BDF0SN
            YP4JJSZske2191b20GGEwLC9M6TdZgVIfEeYa1FagDu7vHAekWItz6YFybgeCn+J
            fqQe10c2GFHWQQ==
            =NuJq
            -----END PGP MESSAGE-----
          fp: 46A08BAEF7DB948F66897A69C6D12C69DB830D3B
    encrypted_regex: ^(ca|crt|id|secret|secretboxEncryptionSecret|secretboxencryptionsecret|token|bootstraptoken|key|environment|TS_AUTHKEY)$
    version: 3.10.2
